services:
    circuit.breaker:
        class: CircuitBreakerBundle\Service\CircuitBreakerService
        arguments: ['@cache.app', '%circuit_breaker.threshold%', '%circuit_breaker.timeout%']
        calls:
            - [setLogger, ['@logger']]

    circuit.breaker.listener:
        class: CircuitBreakerBundle\Listener\CircuitBreakerListener
        arguments: ['@circuit.breaker']
        tags:
            - { name: kernel.event_listener, event: circuit.breaker, method: onCircuitBreaker, priority: 1  }
